/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/rustonbsd/corekv/badger_ffi/ffi/cshared */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdint.h>
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void badger_ffi_free(void* ptr);
extern int32_t badger_ffi_db_open(char* dir, char* valueDir, uint8_t inMemory, uint8_t* encryptionKey, size_t encryptionKeyLen, long long int indexCacheSize, long long int valueLogFileSize, uint64_t* outHandle, char** errOut);
extern int32_t badger_ffi_db_close(uint64_t handle, char** errOut);
extern int32_t badger_ffi_db_drop_all(uint64_t handle, char** errOut);
extern int32_t badger_ffi_db_new_txn(uint64_t handle, uint8_t readOnly, uint64_t* outHandle, char** errOut);
extern int32_t badger_ffi_txn_get(uint64_t handle, uint8_t* key, size_t keyLen, uint8_t** outValue, size_t* outValueLen, char** errOut);
extern int32_t badger_ffi_txn_has(uint64_t handle, uint8_t* key, size_t keyLen, uint8_t* outHas, char** errOut);
extern int32_t badger_ffi_txn_set(uint64_t handle, uint8_t* key, size_t keyLen, uint8_t* value, size_t valueLen, char** errOut);
extern int32_t badger_ffi_txn_delete(uint64_t handle, uint8_t* key, size_t keyLen, char** errOut);
extern int32_t badger_ffi_txn_commit(uint64_t handle, char** errOut);
extern void badger_ffi_txn_discard(uint64_t handle);
extern int32_t badger_ffi_txn_iterator(uint64_t handle, uint8_t* prefix, size_t prefixLen, uint8_t* start, size_t startLen, uint8_t* end, size_t endLen, uint8_t reverse, uint8_t keysOnly, uint64_t* outHandle, char** errOut);
extern int32_t badger_ffi_iter_next(uint64_t handle, uint8_t* outHas, char** errOut);
extern int32_t badger_ffi_iter_key(uint64_t handle, uint8_t** outKey, size_t* outKeyLen, char** errOut);
extern int32_t badger_ffi_iter_value(uint64_t handle, uint8_t** outValue, size_t* outValueLen, char** errOut);
extern int32_t badger_ffi_iter_seek(uint64_t handle, uint8_t* key, size_t keyLen, uint8_t* outHas, char** errOut);
extern int32_t badger_ffi_iter_reset(uint64_t handle, char** errOut);
extern int32_t badger_ffi_iter_close(uint64_t handle, char** errOut);

#ifdef __cplusplus
}
#endif
